import json
from typing import Optional, Collection, Tuple, Mapping

from ausweiskopie.editor.model import FieldLocation
from ausweiskopie.redact import Location, Field


class BaseExporter:
    """ Generic base class to handle exporting documents """
    def export(self, field_locations: Collection[FieldLocation]) -> str:
        raise NotImplementedError()

    @staticmethod
    def get_supported_file_extensions():
        raise NotImplementedError()

    @staticmethod
    def get_default_file_extension():
        raise NotImplementedError()

    @staticmethod
    def get_export_label():
        raise NotImplementedError()

    @staticmethod
    def _group_by_field(field_locations: Collection[FieldLocation]) -> dict[Field, list[Location]]:
        grouped_fields: dict[Field, list[Location]] = {}
        for field_location in field_locations:
            if field_location.field not in grouped_fields:
                grouped_fields[field_location.field] = [field_location.location]
            else:
                grouped_fields[field_location.field].append(field_location.location)

        return grouped_fields


class PythonExporter(BaseExporter):
    placeholder = '### PLACEHOLDER ###'
    output_template = '''# This file has been generated by the Ausweiskopie Editor
from ausweiskopie.redact.definitions import FieldDefinition, Field, Location

# TODO: Provide a proper name for your field definition
FIELDS_EXPORTED: FieldDefinition = {
### PLACEHOLDER ###
}
'''

    def export(self, field_locations: Collection[FieldLocation]) -> str:
        grouped_fields = BaseExporter._group_by_field(field_locations)

        fields = [self._export_field_group(field, locations) for field, locations in grouped_fields.items()]
        fields_code = str.join('\n', fields)

        return PythonExporter.output_template.replace(PythonExporter.placeholder, fields_code)

    @staticmethod
    def _export_field_group(field: Field, locations: list[Location]) -> str:
        locations = [f'Location({l})' for l in locations]
        return f'''    Field.{field}: (
        {str.join(',\n        ', locations)},
    ),'''

    @staticmethod
    def get_supported_file_extensions() -> list[Tuple[str, str]]:
        return [
            ("Python Script", "*.py"),
        ]

    @staticmethod
    def get_default_file_extension() -> str:
        return ".py"

    @staticmethod
    def get_export_label() -> str:
        return 'EDITOR_FORMAT_PYTHON'


class BasicJsonExporter(BaseExporter):

    def export(self, field_locations: Collection[FieldLocation]) -> str:
        grouped_fields = BaseExporter._group_by_field(field_locations)

        json_fields = {
            key: [{
                'top_left': [l.top_left[0], l.top_left[1]],
                'bottom_right': [l.bottom_right[0], l.bottom_right[1]]
            } for l in locations] for key, locations in grouped_fields.items()
        }
        return json.dumps(json_fields, indent=2)

    @staticmethod
    def get_supported_file_extensions():
        return [
            ("JSON Document", "*.json"),
        ]

    @staticmethod
    def get_default_file_extension():
        return ".json"

    @staticmethod
    def get_export_label():
        return 'EDITOR_FORMAT_BASIC_JSON'


EXPORTERS: Mapping[str, BaseExporter] = {
    'python': PythonExporter(),
    'json': BasicJsonExporter(),
}


def get_exporter(exporter_name: str) -> Optional[BaseExporter]:
    if exporter_name not in EXPORTERS:
        return None
    return EXPORTERS[exporter_name]
