import json
from abc import ABCMeta, abstractmethod
from typing import Optional, Collection, Tuple, Mapping

from ausweiskopie.editor.model import FieldLocation
from ausweiskopie.redact import Location, Field


class BaseExporter(metaclass=ABCMeta):
    """ Generic base class to handle exporting layouts """

    @abstractmethod
    def export(self, field_locations: Collection[FieldLocation]) -> str:
        """
        Takes the given field locations and converts them into an exportable layout
        as a string.
        :param field_locations: FieldLocation objects to export
        :return:
        """
        pass

    @property
    @abstractmethod
    def supported_file_extensions(self):
        """
        Returns a list of supported file extensions.
        The tuple to provide shall contain a label and a file extension glob.
        :return:
        """
        pass

    @property
    @abstractmethod
    def default_file_extension(self):
        """
        Returns the default file extension (`.xyz`)
        :return:
        """
        pass

    @property
    @abstractmethod
    def label(self):
        """
        Returns the translation key providing the name of the file format
        :return:
        """
        pass

    @staticmethod
    def _group_by_field(field_locations: Collection[FieldLocation]) -> dict[Field, list[Location]]:
        grouped_fields: dict[Field, list[Location]] = {}
        for field_location in field_locations:
            if field_location.field not in grouped_fields:
                grouped_fields[field_location.field] = [field_location.location]
            else:
                grouped_fields[field_location.field].append(field_location.location)

        return grouped_fields


class PythonExporter(BaseExporter):
    """
    Exports data to a Python snippet
    """

    placeholder = '### PLACEHOLDER ###'
    output_template = '''# This file has been generated by the Ausweiskopie Editor
from ausweiskopie.redact.definitions import FieldDefinition, Field, Location

# TODO: Provide a proper name for your field definition
FIELDS_EXPORTED: FieldDefinition = {
### PLACEHOLDER ###
}
'''

    def export(self, field_locations: Collection[FieldLocation]) -> str:
        grouped_fields = BaseExporter._group_by_field(field_locations)

        fields = [self._export_field_group(field, locations) for field, locations in grouped_fields.items()]
        fields_code = str.join('\n', fields)

        return PythonExporter.output_template.replace(PythonExporter.placeholder, fields_code)

    @staticmethod
    def _export_field_group(field: Field, locations: list[Location]) -> str:
        locations = [f'Location({l})' for l in locations]
        locations_str = str.join(',\n        ', locations)
        return f'''    Field.{field}: (
        {locations_str},
    ),'''

    @property
    def supported_file_extensions(self) -> list[Tuple[str, str]]:
        return [
            ("Python Script", "*.py"),
        ]

    @property
    def default_file_extension(self) -> str:
        return ".py"

    @property
    def label(self) -> str:
        return 'EDITOR_FORMAT_PYTHON'


class BasicJsonExporter(BaseExporter):
    """
    Exports data to a basic JSON format
    """
    def export(self, field_locations: Collection[FieldLocation]) -> str:
        grouped_fields = BaseExporter._group_by_field(field_locations)

        json_fields = {
            key: [{
                'top_left': [l.top_left[0], l.top_left[1]],
                'bottom_right': [l.bottom_right[0], l.bottom_right[1]]
            } for l in locations] for key, locations in grouped_fields.items()
        }
        return json.dumps(json_fields, indent=2)

    @property
    def supported_file_extensions(self):
        return [
            ("JSON Document", "*.json"),
        ]

    @property
    def default_file_extension(self):
        return ".json"

    @property
    def label(self):
        return 'EDITOR_FORMAT_BASIC_JSON'


EXPORTERS: Mapping[str, BaseExporter] = {
    'python': PythonExporter(),
    'json': BasicJsonExporter(),
}


def get_exporter(exporter_name: str) -> Optional[BaseExporter]:
    if exporter_name not in EXPORTERS:
        return None
    return EXPORTERS[exporter_name]
